### ISSUE TITLE
Error when compiling for ARM64?

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#160]
I'm getting the following error when trying to compile Store packages for ARM64. Any idea what could be the cause?

`Package Q42.HueApi 3.8.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-arm-aot. Package Q42.HueApi 3.8.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)	`

**Comment by michielpost** [comment]
Q42.HueApi version 3.8.1 now targets netstandard2.0 instead of 1.1.
Some older pakages are removed, like Q42.HueApi.WinRT.

For UWP apps, netstandard2.0 is available since the Windows Fal Creators Update. So you're UWP app has to target a minimum version of 16299. See https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/

**Comment by niels9001** [comment]
Ah yes, changing the target version to FCU solved the issue. My background components were still targetting AU! Closing the issue, thanks!
