### ISSUE TITLE
Question: Can StreamingApi handle multiple clients?

### ISSUE THREAD

**Issue by TripleNico** [Q42/Q42.HueApi#256]
Quick question; today i tried to use the Entertainment Api from two different computers (clients). The first one connects without any issues and works fine. The second one however fail with a timeout at [StreamingHueClient.Connect](https://github.com/Q42/Q42.HueApi/blob/b527550d3647d46d8335c9f9ab2a263f63daf05e/src/Q42.HueApi.Streaming/StreamingHueClient.cs#L61)

So that made me wonder if a multi-client setup is supported by the Entertainment API?

**Comment by TripleNico** [comment]
Thanks for the answer, although I hoped otherwise ;-) Is there a document page on DeveloperHue of this (maybe i missed it?)?

**Comment by michielpost** [comment]
https://developers.meethue.com/develop/hue-entertainment/philips-hue-entertainment-api/

`Only one stream can be active for an entertainment area, the owner field in the entertainment area indicates the application which activated the stream and is streaming towards the area.`
and
`Only one streaming at a time can take place, otherwise performance may degrade`

There are no limitations to do multiple streams in this library.
