### ISSUE TITLE
Remote Hue API V2 support  - V1 is deprecated

### ISSUE THREAD

**Issue by niels9001** [Q42/Q42.HueApi#72]
Would be cool to have the new Remote Hue V2 in this API as well: it now gives back the same URLs as the local API, just the URL is different!

http://www.developers.meethue.com/documentation/remote-hue-api-v2

**Comment by michielpost** [comment]
Will have a look at this tomorrow. Probably not a lot of work because the current RemoteApi implementation already expects the same Json as the local API.

**Comment by michielpost** [comment]
I added support for the Remote API v2. However, I don't have access to the Remote API myself, so unable to test it. Current support is based on the documentation provided by Philips.

Can you checkout the code and do some testing?

I'd also like to know what the json response is for this call:
https://api.meethue.com/v2/bridges (with your authorization bearer). If you send me the json response I can add support for that.

If you have the authorization bearer and a bridgeId, I assume everything will work fine because then everything behaves just like the local bridge API.

**Comment by niels9001** [comment]
Yep, will do this! Can you package this latest release into a new NuGet release as well so I can update APIs in my app?

**Comment by michielpost** [comment]
Released as v3.0.0
https://github.com/Q42/Q42.HueApi/releases/tag/3.0.0

I'll close this issue. You can create new issues if there are problems with the remote API.
